---

- name: "Deploy APP's on Kubernetes"
  hosts: master
  pre_tasks:
   - setup:
      gather_subset:
       - '!all'
       - '!any'
       - 'network'
       - 'virtual'

  roles:
    - {role: common, tags: "common"}

  tasks:
  - include_role:
      role: app_info
      vars_from: "{{ item }}"
    with_items:
      - app_1.yml
      - app_2.yml
      - app_3.yml
      - app_4.yml
      - app_5.yml
