---
- name: "Check API's on Kubernetes"
  shell: |
    kubectl get all -n qa
  register: check_apis

- name: "Deploy API's on Kubernetes"
  shell: |
    kubectl apply -f /tmp/apis/qa/deployment/{{ item }}.yaml
    kubectl apply -f /tmp/apis/qa/service/{{ item }}.yaml
    kubectl apply -f /tmp/apis/qa/hpa/{{ item }}.yaml
  loop: "{{ api_name }}"
  when: 
    - (check_apis.stderr == "No resources found.")
    - (api_deploy == true)