---
- name: "Check API's on Kubernetes"
  shell: |
    kubectl get all -n {{ item }}
  register: check_apis
  loop: "{{ app_name }}"

- name: "Delete API's on Kubernetes"
  shell: |
    kubectl delete -f /tmp/{{ item }}/deployment/{{ item }}.yaml
    kubectl delete -f /tmp/{{ item }}/service/{{ item }}.yaml
    kubectl delete -f /tmp/{{ item }}/hpa/{{ item }}.yaml
    kubectl delete namespace {{ item }}
  loop: "{{ app_name }}"
  when: 
    - (check_apis.stderr != "No resources found.")
    - (api_deploy == false)